Label Encoding:
converting the labels into numeric form

In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [3]:
df=pd.read_csv("/content/data (1).csv")
df.head()

         id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [11]:
cancer=df.drop('Unnamed: 32',axis=1)

In [10]:
cancer.head()

         id diagnosis  ...  symmetry_worst  fractal_dimension_worst
0    842302         M  ...          0.4601                  0.11890
1    842517         M  ...          0.2750                  0.08902
2  84300903         M  ...          0.3613                  0.08758
3  84348301         M  ...          0.6638                  0.17300
4  84358402         M  ...          0.2364                  0.07678

[5 rows x 32 columns]

In [13]:
cancer.isnull().sum()

id                         0
diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [15]:
cancer['diagnosis'].value_counts()

B    357
M    212
Name: diagnosis, dtype: int64

In [16]:
#load the label encoder function
label=LabelEncoder()

In [17]:
labels=label.fit_transform(cancer.diagnosis)

In [18]:
#appending the labels to the data frame
cancer['target']=labels
cancer.head()

         id diagnosis  ...  fractal_dimension_worst  target
0    842302         M  ...                  0.11890       1
1    842517         M  ...                  0.08902       1
2  84300903         M  ...                  0.08758       1
3  84348301         M  ...                  0.17300       1
4  84358402         M  ...                  0.07678       1

[5 rows x 33 columns]

In [23]:
cancer['target'].value_counts()

0    357
1    212
Name: target, dtype: int64